export interface Product {
  id: string
  name: string
  price: number
  original_price?: number | null
  image_urls: string[]
  thumbnail_url?: string | null
  category_id: string
  rating: number
  review_count: number
  stock_quantity: number
  description: string
  in_stock: boolean
}

export const mockProducts: Product[] = Object.freeze([
  {
    id: '1',
    name: 'Luxury Face Serum',
    price: 2500,
    original_price: 3500,
    image_urls: ['/product-serum.jpg'],
    thumbnail_url: '/product-serum.jpg',
    category_id: '1',
    rating: 4.8,
    review_count: 124,
    stock_quantity: 45,
    description: 'Premium hydrating serum with vitamin C and hyaluronic acid. Reduces fine lines and brightens complexion.',
    in_stock: true,
  },
  {
    id: '2',
    name: 'Matte Lipstick - Berry Kiss',
    price: 1200,
    original_price: 1800,
    image_urls: ['/product-lipstick.jpg'],
    thumbnail_url: '/product-lipstick.jpg',
    category_id: '2',
    rating: 4.6,
    review_count: 89,
    stock_quantity: 60,
    description: 'Long-lasting matte finish lipstick in berry tones. 12-hour wear with vibrant color payoff.',
    in_stock: true,
  },
  {
    id: '3',
    name: 'Hair Growth Oil',
    price: 1800,
    original_price: 2500,
    image_urls: ['/product-oil.jpg'],
    thumbnail_url: '/product-oil.jpg',
    category_id: '3',
    rating: 4.9,
    review_count: 156,
    stock_quantity: 35,
    description: 'Natural oils for stronger, healthier hair growth. Reduces hair fall and promotes thickness.',
    in_stock: true,
  },
  {
    id: '4',
    name: 'Brightening Face Mask',
    price: 2000,
    original_price: 2800,
    image_urls: ['/product-mask.jpg'],
    thumbnail_url: '/product-mask.jpg',
    category_id: '1',
    rating: 4.7,
    review_count: 102,
    stock_quantity: 28,
    description: 'Clay-based mask for bright and glowing skin. Detoxifies and purifies in 15 minutes.',
    in_stock: true,
  },
  {
    id: '5',
    name: 'Foundation - Fair',
    price: 1500,
    original_price: 2200,
    image_urls: ['/product-foundation.jpg'],
    thumbnail_url: '/product-foundation.jpg',
    category_id: '2',
    rating: 4.5,
    review_count: 78,
    stock_quantity: 52,
    description: 'Full coverage foundation with SPF 15. Smooth finish that lasts all day.',
    in_stock: true,
  },
  {
    id: '6',
    name: 'Argan Hair Conditioner',
    price: 1400,
    original_price: 1900,
    image_urls: ['/product-oil.jpg'],
    thumbnail_url: '/product-oil.jpg',
    category_id: '3',
    rating: 4.8,
    review_count: 143,
    stock_quantity: 41,
    description: 'Deep conditioning treatment for silky smooth hair. Rich in argan oil and keratin.',
    in_stock: true,
  },
  {
    id: '7',
    name: 'Vitamin C Eye Cream',
    price: 2200,
    original_price: 3000,
    image_urls: ['/product-eyecream.jpg'],
    thumbnail_url: '/product-eyecream.jpg',
    category_id: '1',
    rating: 4.7,
    review_count: 95,
    stock_quantity: 30,
    description: 'Brightening eye cream for dark circles. Reduces puffiness and fine lines around eyes.',
    in_stock: true,
  },
  {
    id: '8',
    name: 'Perfume - Floral Bliss',
    price: 3500,
    original_price: 4500,
    image_urls: ['/product-perfume.jpg'],
    thumbnail_url: '/product-perfume.jpg',
    category_id: '5',
    rating: 4.9,
    review_count: 210,
    stock_quantity: 25,
    description: 'Elegant floral fragrance for all occasions. Long-lasting 8+ hour wear.',
    in_stock: true,
  },
  {
    id: '9',
    name: 'Luxury Face Moisturizer',
    price: 2200,
    original_price: 3200,
    image_urls: ['/product-moisturizer.jpg'],
    thumbnail_url: '/product-moisturizer.jpg',
    category_id: '1',
    rating: 4.7,
    review_count: 118,
    stock_quantity: 38,
    description: 'Deep hydrating cream with peptides. Restores skin elasticity and radiance.',
    in_stock: true,
  },
  {
    id: '10',
    name: 'Liquid Concealer',
    price: 1300,
    original_price: 1900,
    image_urls: ['/product-concealer.jpg'],
    thumbnail_url: '/product-concealer.jpg',
    category_id: '2',
    rating: 4.6,
    review_count: 92,
    stock_quantity: 55,
    description: 'Full coverage liquid concealer. Lightweight and long-wearing formula.',
    in_stock: true,
  },
  {
    id: '11',
    name: 'Premium Body Lotion',
    price: 1100,
    original_price: 1600,
    image_urls: ['/product-lotion.jpg'],
    thumbnail_url: '/product-lotion.jpg',
    category_id: '4',
    rating: 4.8,
    review_count: 167,
    stock_quantity: 48,
    description: 'Nourishing body lotion with shea butter. Leaves skin soft and smooth.',
    in_stock: true,
  },
  {
    id: '12',
    name: 'Powder Blush - Rose Gold',
    price: 950,
    original_price: 1400,
    image_urls: ['/product-blush.jpg'],
    thumbnail_url: '/product-blush.jpg',
    category_id: '2',
    rating: 4.7,
    review_count: 145,
    stock_quantity: 70,
    description: 'Silky powder blush with natural flush effect. Blends seamlessly.',
    in_stock: true,
  },
])

export const categories = Object.freeze([
  { id: '1', name: 'Skincare', slug: 'skincare', image: '/category-skincare.jpg' },
  { id: '2', name: 'Makeup', slug: 'makeup', image: '/category-makeup.jpg' },
  { id: '3', name: 'Haircare', slug: 'haircare', image: '/category-haircare.jpg' },
  { id: '4', name: 'Body Care', slug: 'body-care', image: '/category-bodycare.jpg' },
  { id: '5', name: 'Fragrances', slug: 'fragrances', image: '/category-fragrances.jpg' },
])
